---

- name: Ensure base Plex directory exists
  ansible.builtin.file:
    path: "{{ plex_docker_base_directory }}"
    state: 'directory'
    owner: "{{ plex_docker_user }}"
    group: "{{ plex_docker_user }}"
    mode: '0755'
  tags:
    - plex
    - plex_setup

- name: Ensure Plex compose file is present
  ansible.builtin.template:
    src: 'compose.yml.j2'
    dest: "{{ plex_docker_base_directory }}/compose.yml"
    owner: "{{ plex_docker_user }}"
    group: "{{ plex_docker_user }}"
    mode: '0644'
    backup: true
  register: plex_docker_compose_template_result
  tags:
    - plex
    - plex_config

- name: Ensure Plex compose project is deployed
  community.docker.docker_compose_v2:
    project_src: "{{ plex_docker_base_directory }}"
    state: 'present'
    recreate: "{{ 'always' if (plex_docker_compose_template_result.changed) else 'auto' }}"
    remove_orphans: true
  tags:
    - plex
    - plex_deploy
